version: "3.8"

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_advertisements
    ports:
      - "5469:5432"
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - job_advertisements_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: job_advertisements_pgadmin
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - job_advertisements_network

volumes:
  db-data:
    driver: local
  pgadmin-data:
    driver: local

networks:
  job_advertisements_network:
    driver: bridge